name: np_async
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  np_collection:
    path: ../np_collection

dev_dependencies:
  np_lints:
    path: ../np_lints
