# This file is a template, and might need editing before it works on your project.
test:
  stage: test
  except:
    - triage
  image: "cirrusci/flutter:3.3.8"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libsqlite3-dev
    - flutter pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - cd app
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/app/coverage
    reports:
      junit: app/report.xml
    expire_in: 6 mos
