// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum ConvertFormat {
  jpeg,
  jxl,
}

class Uploadable {
  Uploadable({
    required this.platformIdentifier,
    required this.endPoint,
    required this.canConvert,
  });

  String platformIdentifier;

  String endPoint;

  bool canConvert;

  Object encode() {
    return <Object?>[
      platformIdentifier,
      endPoint,
      canConvert,
    ];
  }

  static Uploadable decode(Object result) {
    result as List<Object?>;
    return Uploadable(
      platformIdentifier: result[0]! as String,
      endPoint: result[1]! as String,
      canConvert: result[2]! as bool,
    );
  }
}

class ConvertConfig {
  ConvertConfig({
    required this.format,
    required this.quality,
    this.downsizeMp,
  });

  ConvertFormat format;

  int quality;

  double? downsizeMp;

  Object encode() {
    return <Object?>[
      format,
      quality,
      downsizeMp,
    ];
  }

  static ConvertConfig decode(Object result) {
    result as List<Object?>;
    return ConvertConfig(
      format: result[0]! as ConvertFormat,
      quality: result[1]! as int,
      downsizeMp: result[2] as double?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ConvertFormat) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is Uploadable) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ConvertConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ConvertFormat.values[value];
      case 130: 
        return Uploadable.decode(readValue(buffer)!);
      case 131: 
        return ConvertConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MyHostApi {
  /// Constructor for [MyHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MyHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> asyncUpload({required String taskId, required List<Uploadable> uploadables, required Map<String, String> httpHeaders, ConvertConfig? convertConfig, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.np_platform_uploader.MyHostApi.asyncUpload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[taskId, uploadables, httpHeaders, convertConfig]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class MyFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void notifyUploadResult(String taskId, Uploadable uploadable, bool isSuccess);

  void notifyTaskComplete(String taskId);

  static void setUp(MyFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyUploadResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyUploadResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_taskId = (args[0] as String?);
          assert(arg_taskId != null,
              'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyUploadResult was null, expected non-null String.');
          final Uploadable? arg_uploadable = (args[1] as Uploadable?);
          assert(arg_uploadable != null,
              'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyUploadResult was null, expected non-null Uploadable.');
          final bool? arg_isSuccess = (args[2] as bool?);
          assert(arg_isSuccess != null,
              'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyUploadResult was null, expected non-null bool.');
          try {
            api.notifyUploadResult(arg_taskId!, arg_uploadable!, arg_isSuccess!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyTaskComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyTaskComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_taskId = (args[0] as String?);
          assert(arg_taskId != null,
              'Argument for dev.flutter.pigeon.np_platform_uploader.MyFlutterApi.notifyTaskComplete was null, expected non-null String.');
          try {
            api.notifyTaskComplete(arg_taskId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
