// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nkming.nc_photos.np_platform_local_media

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class QueryResult (
  val id: String,
  val displayName: String? = null,
  val dateModified: Long? = null,
  val mimeType: String? = null,
  val dateTaken: Long? = null,
  val width: Long? = null,
  val height: Long? = null,
  val size: Long? = null,
  val androidUri: String? = null,
  val androidPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueryResult {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String?
      val dateModified = pigeonVar_list[2] as Long?
      val mimeType = pigeonVar_list[3] as String?
      val dateTaken = pigeonVar_list[4] as Long?
      val width = pigeonVar_list[5] as Long?
      val height = pigeonVar_list[6] as Long?
      val size = pigeonVar_list[7] as Long?
      val androidUri = pigeonVar_list[8] as String?
      val androidPath = pigeonVar_list[9] as String?
      return QueryResult(id, displayName, dateModified, mimeType, dateTaken, width, height, size, androidUri, androidPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      dateModified,
      mimeType,
      dateTaken,
      width,
      height,
      size,
      androidUri,
      androidPath,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueryResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is QueryResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MyHostApi {
  fun getFilesSummary(dirWhitelist: List<String>?, callback: (Result<Map<String, Long>>) -> Unit)
  fun queryFiles(fileIds: List<String>?, timeRangeBeg: Long?, isTimeRangeBegInclusive: Boolean?, timeRangeEnd: Long?, isTimeRangeEndInclusive: Boolean?, dirWhitelist: List<String>?, isAscending: Boolean, offset: Long?, limit: Long?, callback: (Result<List<QueryResult>>) -> Unit)
  /**
   * Read the content of a file identified by [platformIdentifier]
   *
   * [platformIdentifier] is platform-specific and should be a value returned
   * in [QueryResult.platformIdentifier].
   */
  fun readFile(platformIdentifier: String, callback: (Result<ByteArray>) -> Unit)
  /**
   * Read the content of an image file, and downscale it to save memory
   *
   * Also see [readFile].
   */
  fun readThumbnail(platformIdentifier: String, width: Long, height: Long, callback: (Result<ByteArray>) -> Unit)

  companion object {
    /** The codec used by MyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.np_platform_local_media.MyHostApi.getFilesSummary$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dirWhitelistArg = args[0] as List<String>?
            api.getFilesSummary(dirWhitelistArg) { result: Result<Map<String, Long>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.np_platform_local_media.MyHostApi.queryFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdsArg = args[0] as List<String>?
            val timeRangeBegArg = args[1] as Long?
            val isTimeRangeBegInclusiveArg = args[2] as Boolean?
            val timeRangeEndArg = args[3] as Long?
            val isTimeRangeEndInclusiveArg = args[4] as Boolean?
            val dirWhitelistArg = args[5] as List<String>?
            val isAscendingArg = args[6] as Boolean
            val offsetArg = args[7] as Long?
            val limitArg = args[8] as Long?
            api.queryFiles(fileIdsArg, timeRangeBegArg, isTimeRangeBegInclusiveArg, timeRangeEndArg, isTimeRangeEndInclusiveArg, dirWhitelistArg, isAscendingArg, offsetArg, limitArg) { result: Result<List<QueryResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.np_platform_local_media.MyHostApi.readFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val platformIdentifierArg = args[0] as String
            api.readFile(platformIdentifierArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.np_platform_local_media.MyHostApi.readThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val platformIdentifierArg = args[0] as String
            val widthArg = args[1] as Long
            val heightArg = args[2] as Long
            api.readThumbnail(platformIdentifierArg, widthArg, heightArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
