// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Image {
  var pixel: FlutterStandardTypedData
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Image? {
    let pixel = pigeonVar_list[0] as! FlutterStandardTypedData
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64

    return Image(
      pixel: pixel,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      pixel,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Metadata {
  var w: Int64
  var h: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Metadata? {
    let w = pigeonVar_list[0] as! Int64
    let h = pigeonVar_list[1] as! Int64

    return Metadata(
      w: w,
      h: h
    )
  }
  func toList() -> [Any?] {
    return [
      w,
      h,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Image.fromList(self.readValue() as! [Any?])
    case 130:
      return Metadata.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Image {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Metadata {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MyHostApi {
  func load(filepath: String, w: Int64?, h: Int64?, completion: @escaping (Result<Image, Error>) -> Void)
  func loadBytes(bytes: FlutterStandardTypedData, w: Int64?, h: Int64?, completion: @escaping (Result<Image, Error>) -> Void)
  func loadMetadata(filepath: String, completion: @escaping (Result<Metadata?, Error>) -> Void)
  func save(img: Image, filepath: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func convertJpeg(filepath: String, w: Int64?, h: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_image_format_jxl.MyHostApi.load\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filepathArg = args[0] as! String
        let wArg: Int64? = nilOrValue(args[1])
        let hArg: Int64? = nilOrValue(args[2])
        api.load(filepath: filepathArg, w: wArg, h: hArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadChannel.setMessageHandler(nil)
    }
    let loadBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_image_format_jxl.MyHostApi.loadBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bytesArg = args[0] as! FlutterStandardTypedData
        let wArg: Int64? = nilOrValue(args[1])
        let hArg: Int64? = nilOrValue(args[2])
        api.loadBytes(bytes: bytesArg, w: wArg, h: hArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadBytesChannel.setMessageHandler(nil)
    }
    let loadMetadataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_image_format_jxl.MyHostApi.loadMetadata\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadMetadataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filepathArg = args[0] as! String
        api.loadMetadata(filepath: filepathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadMetadataChannel.setMessageHandler(nil)
    }
    let saveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_image_format_jxl.MyHostApi.save\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imgArg = args[0] as! Image
        let filepathArg = args[1] as! String
        api.save(img: imgArg, filepath: filepathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveChannel.setMessageHandler(nil)
    }
    let convertJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_image_format_jxl.MyHostApi.convertJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filepathArg = args[0] as! String
        let wArg: Int64? = nilOrValue(args[1])
        let hArg: Int64? = nilOrValue(args[2])
        api.convertJpeg(filepath: filepathArg, w: wArg, h: hArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      convertJpegChannel.setMessageHandler(nil)
    }
  }
}
